name: shalom
description: A new Flutter application.


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flappy_search_bar: ^1.7.2
  rounded_floating_app_bar: 0.1.0
  english_words: ^3.1.3




flutter:
  uses-material-design: true
  assets:
    - images/cross.jpg
    - images/internal.jpg
    - images/
  fonts:
    - family: Pacifico
      fonts:
         - asset: fonts/Pacifico-Regular.ttf
    - family: Source Sans Pro
      fonts:
         - asset: fonts/SourceSansPro-Regular.ttf


